# Generated by Django 4.2.5 on 2023-10-02 07:15

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="product", name="subcategory"),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="products.category", verbose_name="Category"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
