# Generated by Django 3.2.18 on 2023-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231020_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category'),
            preserve_default=False,
        ),
    ]
