# Generated by Django 3.2.18 on 2023-10-20 08:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('products', '0006_category_image')]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='subcategory'),
            preserve_default=False,
        )
    ]
