# Generated by Django 4.2.6 on 2023-10-20 09:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20231020_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
