# Generated by Django 4.2.6 on 2023-10-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('products', '0011_alter_product_slug')]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={'verbose_name_plural': 'TopCategories'},
        ),
        migrations.AddField(
            model_name='product',
            name='top_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='products.topcategory',
                verbose_name='topcategories',
            ),
        ),
    ]
